services:
  broker:
    image: apache/kafka:3.9.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  
  pd-cred:
    image: pingcap/pd:v8.5.1
    container_name: pd-cred
    command:
      - --name=pd-cred
      - --data-dir=/data/pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd-cred:2379
      - --advertise-peer-urls=http://pd-cred:2380
      - --initial-cluster=pd-cred=http://pd-cred:2380
    ports:
      - "2379:2379"
    restart: unless-stopped

  tikv-cred:
    image: pingcap/tikv:v8.5.1
    container_name: tikv-cred
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv-cred:20160
      - --data-dir=/data/tikv
      - --pd=pd-cred:2379
    depends_on:
      - pd-cred
    restart: unless-stopped

  tidb-cred:
    image: pingcap/tidb:v8.5.1
    container_name: tidb-cred
    command:
      - --store=tikv
      - --path=pd-cred:2379
    ports:
      - "4000:4000"
      - "10080:10080"
    depends_on:
      - pd-cred
      - tikv-cred
    restart: unless-stopped

  pd-pol:
    image: pingcap/pd:v8.5.1
    container_name: pd-pol
    command:
      - --name=pd-pol
      - --data-dir=/data/pd
      - --client-urls=http://0.0.0.0:3379
      - --peer-urls=http://0.0.0.0:3380
      - --advertise-client-urls=http://pd-pol:3379
      - --advertise-peer-urls=http://pd-pol:3380
      - --initial-cluster=pd-pol=http://pd-pol:3380
    ports:
      - "3379:3379"
    restart: unless-stopped

  tikv-pol:
    image: pingcap/tikv:v8.5.1
    container_name: tikv-pol
    command:
      - --addr=0.0.0.0:30160
      - --advertise-addr=tikv-pol:30160
      - --data-dir=/data/tikv
      - --pd=pd-pol:3379
    depends_on:
      - pd-pol
    restart: unless-stopped

  tidb-pol:
    image: pingcap/tidb:v8.5.1
    container_name: tidb-pol
    command:
      - --store=tikv
      - --path=pd-pol:3379
    ports:
      - "5000:5000"
      - "11080:11080"
    depends_on:
      - pd-pol
      - tikv-pol
    restart: unless-stopped

  pd-ass:
    image: pingcap/pd:v8.5.1
    container_name: pd-ass
    command:
      - --name=pd-ass
      - --data-dir=/data/pd
      - --client-urls=http://0.0.0.0:4379
      - --peer-urls=http://0.0.0.0:4380
      - --advertise-client-urls=http://pd-ass:4379
      - --advertise-peer-urls=http://pd-ass:4380
      - --initial-cluster=pd-ass=http://pd-ass:4380
    ports:
      - "4379:4379"
    restart: unless-stopped

  tikv-ass:
    image: pingcap/tikv:v8.5.1
    container_name: tikv-ass
    command:
      - --addr=0.0.0.0:40160
      - --advertise-addr=tikv-ass:40160
      - --data-dir=/data/tikv
      - --pd=pd-ass:4379
    depends_on:
      - pd-ass
    restart: unless-stopped

  tidb-ass:
    image: pingcap/tidb:v8.5.1
    container_name: tidb-ass
    command:
      - --store=tikv
      - --path=pd-ass:4379
    ports:
      - "6000:6000"
      - "12080:12080"
    depends_on:
      - pd-ass
      - tikv-ass
    restart: unless-stopped

  admin-tomcat:
    image: tomcat:9.0.100-jdk21-corretto
    ports:
      - "8080:8080"
    container_name: admin-tomcat
    volumes:
      - ./admin-tomcat/webapps:/usr/local/tomcat/webapps
      - ./admin-tomcat/logs/:/usr/local/tomcat/logs/
    restart: unless-stopped
    
  api-tomcat:
    image: tomcat:9.0.100-jdk21-corretto
    ports:
      - "80:8080"
    container_name: admin-api
    volumes:
      - ./api-tomcat/webapps:/usr/local/tomcat/webapps
      - ./api-tomcat/logs/:/usr/local/tomcat/logs/
    restart: unless-stopped