plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.sparkjava:spark-core:2.9.4'
    implementation 'com.google.code.gson:gson:2.10.1' // optional, for JSON
    implementation 'ch.qos.logback:logback-classic:1.4.14'

}

application {
    mainClass = 'app.Main'
}

